### PR TITLE
Bump runtime version

### PR DESCRIPTION
**Pull request by axtloss**
Bumps the runtime to `22.08`

### CODE REVIEW

**Comment by wez** [comment]
Once you are satisfied that this builds, note that the source of truth for this file is really https://github.com/wez/wezterm/blob/main/assets/flatpak/org.wezfurlong.wezterm.template.json which will be used to overwrite the one here in the flathub repo by automation when the next wezterm release is tagged.

**Comment by axtloss** [comment]
> Once you are satisfied that this builds, note that the source of truth for this file is really https://github.com/wez/wezterm/blob/main/assets/flatpak/org.wezfurlong.wezterm.template.json which will be used to overwrite the one here in the flathub repo by automation when the next wezterm release is tagged.

Oh ok I will open a PR on the wezterm repo too.

It may be a good idea to add this in a readme on this repo in case someone else wants to contribute changes to the manifest.

**Comment by axtloss** [comment]
I opened a pr in the main wezterm repo https://github.com/wez/wezterm/pull/3550

**Comment by wez** [comment]
I can try merging this here to this repo. I'm not sure if other machinery will prevent pushing an updated version of the package without bumping some other version number in the metadata. If that is the case, then this change won't ship until I tag a new wezterm version

**Comment by wez** [comment]
It let me publish it without bumping a version number!

**Pull request merged**
